# DO NOT MODIFY THIS FILE
# Generated by Bundler 0.9.25

require 'digest/sha1'
require 'yaml'
require 'pathname'
require 'rubygems'
Gem.source_index # ensure Rubygems is fully loaded in Ruby 1.9

module Gem
  class Dependency
    if !instance_methods.map { |m| m.to_s }.include?("requirement")
      def requirement
        version_requirements
      end
    end
  end
end

module Bundler
  class Specification < Gem::Specification
    attr_accessor :relative_loaded_from

    def self.from_gemspec(gemspec)
      spec = allocate
      gemspec.instance_variables.each do |ivar|
        spec.instance_variable_set(ivar, gemspec.instance_variable_get(ivar))
      end
      spec
    end

    def loaded_from
      return super unless relative_loaded_from
      source.path.join(relative_loaded_from).to_s
    end

    def full_gem_path
      Pathname.new(loaded_from).dirname.expand_path.to_s
    end
  end

  module SharedHelpers
    attr_accessor :gem_loaded

    def default_gemfile
      gemfile = find_gemfile
      gemfile or raise GemfileNotFound, "Could not locate Gemfile"
      Pathname.new(gemfile)
    end

    def in_bundle?
      find_gemfile
    end

    def env_file
      default_gemfile.dirname.join(".bundle/environment.rb")
    end

  private

    def find_gemfile
      return ENV['BUNDLE_GEMFILE'] if ENV['BUNDLE_GEMFILE']

      previous = nil
      current  = File.expand_path(Dir.pwd)

      until !File.directory?(current) || current == previous
        filename = File.join(current, 'Gemfile')
        return filename if File.file?(filename)
        current, previous = File.expand_path("..", current), current
      end
    end

    def clean_load_path
      # handle 1.9 where system gems are always on the load path
      if defined?(::Gem)
        me = File.expand_path("../../", __FILE__)
        $LOAD_PATH.reject! do |p|
          next if File.expand_path(p).include?(me)
          p != File.dirname(__FILE__) &&
            Gem.path.any? { |gp| p.include?(gp) }
        end
        $LOAD_PATH.uniq!
      end
    end

    def reverse_rubygems_kernel_mixin
      # Disable rubygems' gem activation system
      ::Kernel.class_eval do
        if private_method_defined?(:gem_original_require)
          alias rubygems_require require
          alias require gem_original_require
        end

        undef gem
      end
    end

    def cripple_rubygems(specs)
      reverse_rubygems_kernel_mixin

      executables = specs.map { |s| s.executables }.flatten
      Gem.source_index # ensure RubyGems is fully loaded

     ::Kernel.class_eval do
        private
        def gem(*) ; end
      end

      ::Kernel.send(:define_method, :gem) do |dep, *reqs|
        if executables.include? File.basename(caller.first.split(':').first)
          return
        end
        opts = reqs.last.is_a?(Hash) ? reqs.pop : {}

        unless dep.respond_to?(:name) && dep.respond_to?(:requirement)
          dep = Gem::Dependency.new(dep, reqs)
        end

        spec = specs.find  { |s| s.name == dep.name }

        if spec.nil?
          e = Gem::LoadError.new "#{dep.name} is not part of the bundle. Add it to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        elsif dep !~ spec
          e = Gem::LoadError.new "can't activate #{dep}, already activated #{spec.full_name}. " \
                                 "Make sure all dependencies are added to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        end

        true
      end

      # === Following hacks are to improve on the generated bin wrappers ===

      # Yeah, talk about a hack
      source_index_class = (class << Gem::SourceIndex ; self ; end)
      source_index_class.send(:define_method, :from_gems_in) do |*args|
        source_index = Gem::SourceIndex.new
        source_index.spec_dirs = *args
        source_index.add_specs(*specs)
        source_index
      end

      # OMG more hacks
      gem_class = (class << Gem ; self ; end)
      gem_class.send(:define_method, :bin_path) do |name, *args|
        exec_name, *reqs = args

        spec = nil

        if exec_name
          spec = specs.find { |s| s.executables.include?(exec_name) }
          spec or raise Gem::Exception, "can't find executable #{exec_name}"
        else
          spec = specs.find  { |s| s.name == name }
          exec_name = spec.default_executable or raise Gem::Exception, "no default executable for #{spec.full_name}"
        end

        gem_bin = File.join(spec.full_gem_path, spec.bindir, exec_name)
        gem_from_path_bin = File.join(File.dirname(spec.loaded_from), spec.bindir, exec_name)
        File.exist?(gem_bin) ? gem_bin : gem_from_path_bin
      end
    end

    extend self
  end
end

module Bundler
  ENV_LOADED   = true
  LOCKED_BY    = '0.9.25'
  FINGERPRINT  = "19bbfadc58fd032dca98f681f56ef9c99ecefd29"
  HOME         = '/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/bundler'
  AUTOREQUIRES = {:default=>[["haml", false], ["compass", true], ["ninesixty", true], ["json", true], ["maruku", false], ["couchrest", true], ["merb-core", false], ["merb-action-args", false], ["merb-assets", false], ["merb-auth-core", false], ["merb-auth-more", false], ["merb-slices", false], ["merb-auth-slice-password", false], ["merb-cache", false], ["merb-mailer", false], ["merb-exceptions", false], ["merb-gen", false], ["merb-haml", false], ["merb-helpers", false], ["merb-param-protection", false], ["merb_viewfu", false], ["thin", false]]}
  SPECS        = [
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249%global/gems/rake-0.8.7/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249%global/specifications/rake-0.8.7.gemspec", :name=>"rake"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/ZenTest-4.3.1/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/ZenTest-4.3.1.gemspec", :name=>"ZenTest"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/RubyInline-3.8.4/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/RubyInline-3.8.4.gemspec", :name=>"RubyInline"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/sexp_processor-3.0.4/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/sexp_processor-3.0.4.gemspec", :name=>"sexp_processor"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/ParseTree-3.0.5/lib", "/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/ParseTree-3.0.5/test"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/ParseTree-3.0.5.gemspec", :name=>"ParseTree"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/abstract-1.0.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/abstract-1.0.0.gemspec", :name=>"abstract"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/bundler-0.9.25/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/bundler-0.9.25.gemspec", :name=>"bundler"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/haml-2.2.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/haml-2.2.0.gemspec", :name=>"haml"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/chriseppstein-compass-0.8.16/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/chriseppstein-compass-0.8.16.gemspec", :name=>"chriseppstein-compass"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/chriseppstein-compass-960-plugin-0.9.8/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/chriseppstein-compass-960-plugin-0.9.8.gemspec", :name=>"chriseppstein-compass-960-plugin"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/daemons-1.0.10/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/daemons-1.0.10.gemspec", :name=>"daemons"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/diff-lcs-1.1.2/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/diff-lcs-1.1.2.gemspec", :name=>"diff-lcs"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/erubis-2.6.5/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/erubis-2.6.5.gemspec", :name=>"erubis"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/eventmachine-0.12.10/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/eventmachine-0.12.10.gemspec", :name=>"eventmachine"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/extlib-0.9.14/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/extlib-0.9.14.gemspec", :name=>"extlib"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/highline-1.5.2/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/highline-1.5.2.gemspec", :name=>"highline"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/json_pure-1.1.9/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/json_pure-1.1.9.gemspec", :name=>"json_pure"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/mime-types-1.16/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/mime-types-1.16.gemspec", :name=>"mime-types"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/mailfactory-1.4.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/mailfactory-1.4.0.gemspec", :name=>"mailfactory"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/syntax-1.0.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/syntax-1.0.0.gemspec", :name=>"syntax"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/maruku-0.6.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/maruku-0.6.0.gemspec", :name=>"maruku"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/rest-client-1.5.1/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/rest-client-1.5.1.gemspec", :name=>"rest-client"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/mattetti-couchrest-0.34/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/mattetti-couchrest-0.34.gemspec", :name=>"mattetti-couchrest"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/rack-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/rack-1.1.0.gemspec", :name=>"rack"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/rspec-1.3.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/rspec-1.3.0.gemspec", :name=>"rspec"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-core-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-core-1.1.0.gemspec", :name=>"merb-core"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/ruby_parser-2.0.4/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/ruby_parser-2.0.4.gemspec", :name=>"ruby_parser"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/ruby2ruby-1.2.4/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/ruby2ruby-1.2.4.gemspec", :name=>"ruby2ruby"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-action-args-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-action-args-1.1.0.gemspec", :name=>"merb-action-args"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-assets-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-assets-1.1.0.gemspec", :name=>"merb-assets"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-auth-core-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-auth-core-1.1.0.gemspec", :name=>"merb-auth-core"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-auth-more-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-auth-more-1.1.0.gemspec", :name=>"merb-auth-more"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-slices-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-slices-1.1.0.gemspec", :name=>"merb-slices"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-auth-slice-password-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-auth-slice-password-1.1.0.gemspec", :name=>"merb-auth-slice-password"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-cache-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-cache-1.1.0.gemspec", :name=>"merb-cache"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-mailer-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-mailer-1.1.0.gemspec", :name=>"merb-mailer"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-exceptions-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-exceptions-1.1.0.gemspec", :name=>"merb-exceptions"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/templater-1.0.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/templater-1.0.0.gemspec", :name=>"templater"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-gen-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-gen-1.1.0.gemspec", :name=>"merb-gen"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-haml-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-haml-1.1.0.gemspec", :name=>"merb-haml"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-helpers-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-helpers-1.1.0.gemspec", :name=>"merb-helpers"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb-param-protection-1.1.0/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb-param-protection-1.1.0.gemspec", :name=>"merb-param-protection"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/merb_viewfu-0.3.4/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/merb_viewfu-0.3.4.gemspec", :name=>"merb_viewfu"},
        {:load_paths=>["/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/gems/thin-1.2.2/lib"], :loaded_from=>"/home/zn_mcms/.rvm/gems/ruby-1.8.7-p249/specifications/thin-1.2.2.gemspec", :name=>"thin"},
      ].map do |hash|
    if hash[:virtual_spec]
      spec = eval(hash[:virtual_spec], TOPLEVEL_BINDING, "<virtual spec for '#{hash[:name]}'>")
    else
      dir = File.dirname(hash[:loaded_from])
      spec = Dir.chdir(dir){ eval(File.read(hash[:loaded_from]), TOPLEVEL_BINDING, hash[:loaded_from]) }
    end
    spec.loaded_from = hash[:loaded_from]
    spec.require_paths = hash[:load_paths]
    if spec.loaded_from.include?(HOME)
      Bundler::Specification.from_gemspec(spec)
    else
      spec
    end
  end

  extend SharedHelpers

  def self.configure_gem_path_and_home(specs)
    # Fix paths, so that Gem.source_index and such will work
    paths = specs.map{|s| s.installation_path }
    paths.flatten!; paths.compact!; paths.uniq!; paths.reject!{|p| p.empty? }
    ENV['GEM_PATH'] = paths.join(File::PATH_SEPARATOR)
    ENV['GEM_HOME'] = paths.first
    Gem.clear_paths
  end

  def self.match_fingerprint
    lockfile = File.expand_path('../../Gemfile.lock', __FILE__)
    lock_print = YAML.load(File.read(lockfile))["hash"] if File.exist?(lockfile)
    gem_print = Digest::SHA1.hexdigest(File.read(File.expand_path('../../Gemfile', __FILE__)))

    unless gem_print == lock_print
      abort 'Gemfile changed since you last locked. Please run `bundle lock` to relock.'
    end

    unless gem_print == FINGERPRINT
      abort 'Your bundled environment is out of date. Run `bundle install` to regenerate it.'
    end
  end

  def self.setup(*groups)
    match_fingerprint
    clean_load_path
    cripple_rubygems(SPECS)
    configure_gem_path_and_home(SPECS)
    SPECS.each do |spec|
      Gem.loaded_specs[spec.name] = spec
      spec.require_paths.each do |path|
        $LOAD_PATH.unshift(path) unless $LOAD_PATH.include?(path)
      end
    end
    self
  end

  def self.require(*groups)
    groups = [:default] if groups.empty?
    groups.each do |group|
      (AUTOREQUIRES[group.to_sym] || []).each do |file, explicit|
        if explicit
          Kernel.require file
        else
          begin
            Kernel.require file
          rescue LoadError
          end
        end
      end
    end
  end

  # Set up load paths unless this file is being loaded after the Bundler gem
  setup unless defined?(Bundler::GEM_LOADED)
end
