---
development: &defaults
  couch_host: http://127.0.0.1:5984
  couch_db: mcms
  merb_serve_static: true
test:
  <<:       *defaults
staging:
  <<:       *defaults
production:
  <<:       *defaults
rake:
  <<: *defaults
